SELECT T2.AUTHOR_ID, T2.AUTHOR_NAME, T1.CATEGORY, SUM(T3.SALES*T1.PRICE) TOTAL_SALES
FROM BOOK T1
INNER JOIN AUTHOR T2
ON T2.AUTHOR_ID = T1.AUTHOR_ID
INNER JOIN BOOK_SALES T3
ON T3.BOOK_ID = T1.BOOK_ID
WHERE TO_CHAR(T3.SALES_DATE, 'YYYYMM') = '202201'
GROUP BY T2.AUTHOR_ID, T2.AUTHOR_NAME, T1.CATEGORY
ORDER BY 1, 3 DESC