SELECT PR.PRODUCT_CODE, SUM(OS.SALES_AMOUNT)*PR.PRICE AS SALES
FROM PRODUCT PR
INNER JOIN OFFLINE_SALE OS
ON OS.PRODUCT_ID = PR.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE, PR.PRICE
ORDER BY SALES DESC, PR.PRODUCT_CODE
