-- SELECT OFS.SALES_DATE, OFS.PRODUCT_ID, USER_ID, OFS.SALES_AMOUNT + ONS.SALES_AMOUNT
-- FROM OFFLINE_SALE OFS
-- LEFT JOIN ONLINE_SALE ONS
-- ON ONS.SALES_DATE = OFS.SALES_DATE
-- ORDER BY 1, 2, 3

SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD'), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
UNION ALL
SELECT TO_CHAR(SALES_DATE,'YYYY-MM-DD'), PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202203'
ORDER BY 1, 2, 3
