
WITH TEMP AS (
SELECT DISTINCT T1.CAR_ID, T1.CAR_TYPE, T1.DAILY_FEE * 30 * (1-T3.DISCOUNT_RATE*0.01) FEE
FROM CAR_RENTAL_COMPANY_CAR T1
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
ON T3.CAR_TYPE = T1.CAR_TYPE
WHERE T3.DURATION_TYPE = '30일 이상')

SELECT DISTINCT CAR_ID, CAR_TYPE, FEE
FROM TEMP
WHERE FEE >= 500000 AND FEE < 2000000
        AND CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01')
        AND CAR_TYPE IN ('세단', 'SUV')
ORDER BY 3 DESC, 2, 1 DESC
