WITH CTE AS (SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, C.DAILY_FEE * 30 * (1-(DP.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON C.CAR_TYPE = DP.CAR_TYPE
WHERE DP.DURATION_TYPE = '30일 이상'
      AND C.CAR_TYPE IN ('세단', 'SUV'))
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, C.FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
INNER JOIN CTE C
ON RH.CAR_ID = C.CAR_ID
WHERE FEE >= 500000 AND FEE < 2000000
      AND C.CAR_ID NOT IN (
        SELECT CAR_ID 
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE TO_CHAR(END_DATE, 'YYYY-MM-DD') >= '2022-11-01'
      )
ORDER BY 3 DESC, 2, 1 DESC