WITH TEMP AS(SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE)

SELECT T1.FOOD_TYPE, T1.REST_ID, T1.REST_NAME, T1.FAVORITES
FROM REST_INFO T1
INNER JOIN TEMP T2
ON T2.FOOD_TYPE = T1.FOOD_TYPE 
AND T2.FAVORITES = T1.FAVORITES
ORDER BY 1 DESC