-- 중고 거래 게시물을 3건 이상 등록한 사용자
WITH TEMP AS (
SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >= 3)


SELECT DISTINCT UGU.USER_ID, 
                UGU.NICKNAME, 
                UGU.CITY || ' ' || UGU.STREET_ADDRESS1 || ' ' || UGU.STREET_ADDRESS2 "전체주소",
                SUBSTR(UGU.TLNO, 1, 3) || '-' || SUBSTR(UGU.TLNO, 4, 4) || '-' || SUBSTR(UGU.TLNO, 8, 4) "전화번호"
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGU
ON UGU.USER_ID = UGB.WRITER_ID
WHERE WRITER_ID IN (SELECT WRITER_ID FROM TEMP)
ORDER BY 1 DESC