-- 상품을 구매한 회원 수
WITH CTE1 AS(SELECT DISTINCT EXTRACT (YEAR FROM OS.SALES_DATE) YEAR, 
             EXTRACT (MONTH FROM OS.SALES_DATE) MONTH, 
             OS.USER_ID 
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS
ON OS.USER_ID = UI.USER_ID
WHERE EXTRACT (YEAR FROM UI.JOINED) = 2021
ORDER BY USER_ID )

-- 2021년 가입한 회원 수
-- WITH CTE2 AS(SELECT COUNT(USER_ID) JOINED_CNT
-- FROM USER_INFO
-- WHERE TO_CHAR(JOINED, 'YYYY') = '2021')

SELECT YEAR, 
        MONTH, 
        COUNT(USER_ID) PUCHASED_USERS, 
ROUND(COUNT(USER_ID)/(SELECT COUNT(*) JOINED_CNT FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) PUCHASED_RATIO
FROM CTE1
GROUP BY YEAR, MONTH
ORDER BY 1, 2

-- SELECT TO_CHAR(SALES_DATE, 'YYYY') YEAR, 
--         TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) MONTH, 
--         COUNT(UI.USER_ID) PUCHASED_USERS, 
--         TO_CHAR(ROUND(COUNT(UI.USER_ID)/(SELECT JOINED_CNT FROM CTE2), 1), 'FM9990.0') PUCHASED_RATIO, 
--         (SELECT JOINED_CNT FROM CTE2)
-- FROM USER_INFO UI
-- INNER JOIN ONLINE_SALE OS
-- ON OS.USER_ID = UI.USER_ID
-- WHERE TO_CHAR(UI.JOINED, 'YYYY') = '2021'
-- GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM')
-- ORDER BY 1, 2