-- 상품을 구매한 회원 수
WITH CTE AS(SELECT DISTINCT EXTRACT (YEAR FROM OS.SALES_DATE) YEAR, 
             EXTRACT (MONTH FROM OS.SALES_DATE) MONTH, 
             OS.USER_ID 
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS
ON OS.USER_ID = UI.USER_ID
WHERE EXTRACT (YEAR FROM UI.JOINED) = 2021
ORDER BY USER_ID )

SELECT YEAR, 
        MONTH, 
        COUNT(USER_ID) PUCHASED_USERS, 
ROUND(COUNT(USER_ID)/(SELECT COUNT(*) JOINED_CNT FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY') = '2021'), 1) PUCHASED_RATIO
FROM CTE
GROUP BY YEAR, MONTH
ORDER BY 1, 2
