WITH CTE AS (SELECT DISTINCT EXTRACT (YEAR FROM OS.SALES_DATE) AS YEAR,
        EXTRACT (MONTH FROM OS.SALES_DATE) AS MONTH,
        OS.USER_ID
FROM USER_INFO UI
INNER JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
WHERE EXTRACT (YEAR FROM UI.JOINED) = '2021')
SELECT YEAR, 
        MONTH, 
        COUNT(USER_ID) AS PURCHASED_USERS, 
        ROUND(COUNT(USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE EXTRACT (YEAR FROM JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM CTE
GROUP BY YEAR, MONTH
ORDER BY 1, 2