SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP
INNER JOIN FOOD_ORDER FO
ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE TO_CHAR(FO.PRODUCE_DATE, 'YYYYMMDD') BETWEEN '20220501' AND '20220531'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID
