SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE*FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
INNER JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE TO_CHAR(FO.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY 3 DESC, 1