WITH CTE AS (SELECT  
             RH.HISTORY_ID,
             RH.END_DATE - RH.START_DATE + 1 AS DATEDIFF,
             C.DAILY_FEE,
             C.CAR_ID,
             C.CAR_TYPE,
                CASE 
                    WHEN RH.END_DATE - RH.START_DATE + 1 BETWEEN 7 AND 29 THEN '7일 이상'
                    WHEN RH.END_DATE - RH.START_DATE + 1 BETWEEN 30 AND 89 THEN '30일 이상'
                    WHEN RH.END_DATE - RH.START_DATE + 1 >= 90 THEN '90일 이상'
                END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON C.CAR_ID = RH.CAR_ID
WHERE C.CAR_TYPE = '트럭')
SELECT C.HISTORY_ID, 
        TRUNC((C.DAILY_FEE * C.DATEDIFF) / 100 * (100 - NVL(DP.DISCOUNT_RATE, 0))) AS FEE
FROM CTE C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
ON C.DURATION_TYPE = DP.DURATION_TYPE
   AND C.CAR_TYPE = DP.CAR_TYPE
ORDER BY 2 DESC, 1 DESC