WITH CTE AS (SELECT T2.HISTORY_ID, T2.END_DATE-T2.START_DATE+1 DAYS, T1.CAR_TYPE,
              T1.DAILY_FEE,
                CASE WHEN T2.END_DATE-T2.START_DATE+1 BETWEEN 7 AND 29 THEN '7일 이상'
                 WHEN T2.END_DATE-T2.START_DATE+1 BETWEEN 30 AND 89 THEN '30일 이상'
                 WHEN T2.END_DATE-T2.START_DATE+1 >= 90 THEN '90일 이상' END DURATION_TYPE
FROM CAR_RENTAL_COMPANY_CAR T1
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
ON T2.CAR_ID = T1.CAR_ID
WHERE T1.CAR_TYPE = '트럭')

SELECT CTE.HISTORY_ID,
       TRUNC((CTE.DAILY_FEE * CTE.DAYS) / 100 * (100 - NVL(PLAN.DISCOUNT_RATE,0))) FEE
FROM CTE CTE
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON CTE.DURATION_TYPE = PLAN.DURATION_TYPE
AND CTE.CAR_TYPE = PLAN.CAR_TYPE
ORDER BY 2 DESC, 1 DESC