WITH TEMP AS(SELECT J.FLAVOR, SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)
FROM FIRST_HALF FH
FULL OUTER JOIN JULY J
ON J.SHIPMENT_ID = FH.SHIPMENT_ID
GROUP BY J.FLAVOR
ORDER BY 2 DESC)

SELECT FLAVOR
FROM TEMP 
FETCH FIRST 3 ROWS ONLY