WITH CTE AS(SELECT LEVEL-1 AS HOUR
FROM DUAL
CONNECT BY LEVEL <= 24)
SELECT C.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM CTE C
LEFT JOIN ANIMAL_OUTS AO
ON C.HOUR = TO_CHAR(AO.DATETIME, 'HH24')
GROUP BY C.HOUR
ORDER BY 1