SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGU
ON UGU.USER_ID = UGB.WRITER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING  SUM(UGB.PRICE) >= 700000
ORDER BY 3