WITH CTE AS (
    SELECT 
       EMP_NO,
       CASE
           WHEN AVG(SCORE) >= 96 THEN 'S'
           WHEN AVG(SCORE) >= 90 THEN 'A'
           WHEN AVG(SCORE) >= 80 THEN 'B'
           ELSE 'C'
       END AS 'GRADE',
       CASE
           WHEN AVG(SCORE) >= 96 THEN 0.2
           WHEN AVG(SCORE) >= 90 THEN 0.15
           WHEN AVG(SCORE) >= 80 THEN 0.1
           ELSE 0
       END AS 'BONUS'
FROM HR_GRADE
GROUP BY EMP_NO)
SELECT HE.EMP_NO, HE.EMP_NAME, C.GRADE, HE.SAL*C.BONUS AS BONUS
FROM HR_EMPLOYEES HE
INNER JOIN CTE C
ON HE.EMP_NO = C.EMP_NO
ORDER BY 1