WITH CTE AS (SELECT MEMBER_ID, COUNT(*) AS CNT
FROM REST_REVIEW
GROUP BY MEMBER_ID),
CTE2 AS (SELECT MEMBER_ID
FROM CTE
WHERE CNT = (SELECT MAX(CNT) FROM CTE))
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (SELECT MEMBER_ID FROM CTE2)
ORDER BY RR.REVIEW_DATE, 2