WITH TEMP AS (SELECT CAR_ID, COUNT(HISTORY_ID) COUNT
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210' 
GROUP BY CAR_ID)

SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, T1.CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
INNER JOIN TEMP T2 
ON T2.CAR_ID = T1.CAR_ID
WHERE T2.COUNT >= 5 AND  TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210' 
GROUP BY EXTRACT(MONTH FROM START_DATE), T1.CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY 1, 2 DESC


-- SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- WHERE CAR_ID IN (SELECT CAR_ID
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
-- WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
-- GROUP BY CAR_ID
-- HAVING COUNT(HISTORY_ID) >= 5)
-- GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
-- HAVING COUNT(HISTORY_ID) > 0
-- ORDER BY 1, 2 DESC 