WITH CTE AS (SELECT 
    YEAR(DIFFERENTIATION_DATE) YEAR,
      MAX(SIZE_OF_COLONY) MAX
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE))
SELECT YEAR(T1.DIFFERENTIATION_DATE) YEAR,
         MAX(T2.MAX-T1.SIZE_OF_COLONY) YEAR_DEV,
         T1.ID
FROM ECOLI_DATA T1
INNER JOIN CTE T2
ON T2.YEAR = YEAR(T1.DIFFERENTIATION_DATE)
GROUP BY T1.ID, YEAR(T1.DIFFERENTIATION_DATE)
ORDER BY 1, 2