SELECT DISTINCT T1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR T1
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY T2
ON T2.CAR_ID = T1.CAR_ID
WHERE T1.CAR_TYPE = '세단' AND TO_CHAR(T2.START_DATE, 'MM') = '10'
ORDER BY 1 DESC