SELECT T1.ID, T2.FISH_NAME, T1.LENGTH
FROM FISH_INFO T1
INNER JOIN FISH_NAME_INFO T2
ON T2.FISH_TYPE = T1.FISH_TYPE
WHERE (T1.FISH_TYPE, T1.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)
ORDER BY 1