SELECT SUM(HG.SCORE) SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
INNER JOIN HR_GRADE HG
ON HG.EMP_NO = HE.EMP_NO
WHERE HG.YEAR = 2022
GROUP BY HE.EMP_NO
ORDER BY SUM(HG.SCORE) DESC
LIMIT 1