SELECT '/home/grep/src/'
       || UGB.BOARD_ID
       || '/'
       || UGF.FILE_ID
       || UGF.FILE_NAME
       || UGF.FILE_EXT FILE_PATH
FROM   USED_GOODS_BOARD UGB
       INNER JOIN USED_GOODS_FILE UGF
               ON UGF.BOARD_ID = UGB.BOARD_ID
WHERE  UGB.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY UGF.FILE_ID DESC