WITH TEMP AS (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY)

SELECT T2.CATEGORY, T2.MAX_PRICE, T1.PRODUCT_NAME
FROM FOOD_PRODUCT T1
INNER JOIN TEMP T2
ON T2.CATEGORY = T1.CATEGORY
AND T2.MAX_PRICE = T1.PRICE
ORDER BY 2 DESC


-- SELECT CATEGORY, MAX(PRICE)
-- FROM FOOD_PRODUCT
-- GROUP BY CATEGORY