WITH CTE AS (SELECT CATEGORY, MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY)
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN (SELECT PRICE FROM CTE)
      AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC