WITH CTE AS (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), CTE2 AS (SELECT
    CASE 
        WHEN SKILL_CODE & (SELECT * FROM CTE) 
            AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'python') THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B' 
        WHEN SKILL_CODE & (SELECT * FROM CTE) THEN 'C'
    END AS GRADE, 
    ID, EMAIL
FROM DEVELOPERS)
SELECT *
FROM CTE2
WHERE GRADE IS NOT NULL
ORDER BY 1, 2